# Available screens:
#-------------------
# Waveshare_epd:
#   waveshare_1.3_v2
#   waveshare_1.3_v3
#   waveshare_1.3_v4
#   waveshare_2.7
#   waveshare_2.7a (partial refresh)
# 
# Luma.oled:
#   luma_oled_spi_128x64
# 
# Luma.lcd:
#   gamepi_1.3_lcd
#   gamepi_1.5_lcd
#   gamepi_1.44_lcd
#   gamepi_1.54_lcd
#   gamepi_2.0_lcd
#   displayhatmini
#   waveshare_3.5_clone
# 

screens:
  screen1:
    name: "displayhatmini"
    #spi_port: 0
    default_input: input1

#  screen2:
#    name: "luma_oled_128x64"
#    address: 0x3C

frame_inputs:
  input1:
    type: "retrieved" # or "received"
    mode: "image"
    name: "pwnagotchi"
    path: "/var/tmp/pwnagotchi/pwnagotchi.png"

#  input2:
#    type: "retrieved" # or "received"
#    name: "terminal"
#    path: "fb0"

