screens:
  screen1:
    name: "displayhatmini" #"waveshare_3.5_clone"
    spi_port: 0
    default_input: input1

#  screen2:
#    name: "luma_oled_128x64"
#    address: 0x3C

frame_inputs:
  input1:
    type: "retrieved" # or "received"
    name: "pwnagotchi"
    path: "/var/tmp/pwnagotchi/pwnagotchi.png"

#  input2:
#    type: "retrieved" # or "received"
#    name: "terminal"
#    path: "fb0"